# Generated by Django 6.0.2 on 2026-06-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Joined', 'Joined')], default='Pending', max_length=20),
        ),
    ]
