# Generated by Django 6.0.2 on 2026-06-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_contactenquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='fitness_goal',
            field=models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain'), ('Muscle Building', 'Muscle Building'), ('Body Transformation', 'Body Transformation'), ('Strength Training', 'Strength Training'), ('General Fitness', 'General Fitness')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='service_required',
            field=models.CharField(choices=[('Gym Membership', 'Gym Membership'), ('Personal Training', 'Personal Training'), ('Nutrition Coaching', 'Nutrition Coaching'), ('Weight Loss Program', 'Weight Loss Program'), ('Weight Gain Program', 'Weight Gain Program'), ('Strength Training', 'Strength Training'), ('Group Fitness Classes', 'Group Fitness Classes')], max_length=50),
        ),
    ]
